// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "KeyValueType.hxx"

#include "DSAKeyValueType.hxx"

#include "RSAKeyValueType.hxx"

namespace oadr2b
{
  namespace sig
  {
    // KeyValueType
    // 

    const KeyValueType::DSAKeyValue_optional& KeyValueType::
    DSAKeyValue () const
    {
      return this->DSAKeyValue_;
    }

    KeyValueType::DSAKeyValue_optional& KeyValueType::
    DSAKeyValue ()
    {
      return this->DSAKeyValue_;
    }

    void KeyValueType::
    DSAKeyValue (const DSAKeyValue_type& x)
    {
      this->DSAKeyValue_.set (x);
    }

    void KeyValueType::
    DSAKeyValue (const DSAKeyValue_optional& x)
    {
      this->DSAKeyValue_ = x;
    }

    void KeyValueType::
    DSAKeyValue (::std::unique_ptr< DSAKeyValue_type > x)
    {
      this->DSAKeyValue_.set (std::move (x));
    }

    const KeyValueType::RSAKeyValue_optional& KeyValueType::
    RSAKeyValue () const
    {
      return this->RSAKeyValue_;
    }

    KeyValueType::RSAKeyValue_optional& KeyValueType::
    RSAKeyValue ()
    {
      return this->RSAKeyValue_;
    }

    void KeyValueType::
    RSAKeyValue (const RSAKeyValue_type& x)
    {
      this->RSAKeyValue_.set (x);
    }

    void KeyValueType::
    RSAKeyValue (const RSAKeyValue_optional& x)
    {
      this->RSAKeyValue_ = x;
    }

    void KeyValueType::
    RSAKeyValue (::std::unique_ptr< RSAKeyValue_type > x)
    {
      this->RSAKeyValue_.set (std::move (x));
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace oadr2b
{
  namespace sig
  {
    // KeyValueType
    //

    KeyValueType::
    KeyValueType ()
    : ::xml_schema::type (),
      DSAKeyValue_ (this),
      RSAKeyValue_ (this)
    {
    }

    KeyValueType::
    KeyValueType (const KeyValueType& x,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      DSAKeyValue_ (x.DSAKeyValue_, f, this),
      RSAKeyValue_ (x.RSAKeyValue_, f, this)
    {
    }

    KeyValueType::
    KeyValueType (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      DSAKeyValue_ (this),
      RSAKeyValue_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void KeyValueType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // DSAKeyValue
        //
        if (n.name () == "DSAKeyValue" && n.namespace_ () == "http://www.w3.org/2000/09/xmldsig#")
        {
          ::std::unique_ptr< DSAKeyValue_type > r (
            DSAKeyValue_traits::create (i, f, this));

          if (!this->DSAKeyValue_)
          {
            this->DSAKeyValue_.set (::std::move (r));
            continue;
          }
        }

        // RSAKeyValue
        //
        if (n.name () == "RSAKeyValue" && n.namespace_ () == "http://www.w3.org/2000/09/xmldsig#")
        {
          ::std::unique_ptr< RSAKeyValue_type > r (
            RSAKeyValue_traits::create (i, f, this));

          if (!this->RSAKeyValue_)
          {
            this->RSAKeyValue_.set (::std::move (r));
            continue;
          }
        }

        break;
      }
    }

    KeyValueType* KeyValueType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class KeyValueType (*this, f, c);
    }

    KeyValueType& KeyValueType::
    operator= (const KeyValueType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->DSAKeyValue_ = x.DSAKeyValue_;
        this->RSAKeyValue_ = x.RSAKeyValue_;
      }

      return *this;
    }

    KeyValueType::
    ~KeyValueType ()
    {
    }
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace oadr2b
{
  namespace sig
  {
    ::std::ostream&
    operator<< (::std::ostream& o, const KeyValueType& i)
    {
      if (i.DSAKeyValue ())
      {
        o << ::std::endl << "DSAKeyValue: " << *i.DSAKeyValue ();
      }

      if (i.RSAKeyValue ())
      {
        o << ::std::endl << "RSAKeyValue: " << *i.RSAKeyValue ();
      }

      return o;
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace oadr2b
{
  namespace sig
  {
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace oadr2b
{
  namespace sig
  {
    void
    operator<< (::xercesc::DOMElement& e, const KeyValueType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // DSAKeyValue
      //
      if (i.DSAKeyValue ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "DSAKeyValue",
            "http://www.w3.org/2000/09/xmldsig#",
            e));

        s << *i.DSAKeyValue ();
      }

      // RSAKeyValue
      //
      if (i.RSAKeyValue ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "RSAKeyValue",
            "http://www.w3.org/2000/09/xmldsig#",
            e));

        s << *i.RSAKeyValue ();
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

