// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "oadrRequestEventType.hxx"

#include "eiRequestEvent.hxx"

#include "schemaVersionType.hxx"

namespace oadr2b
{
  namespace oadr
  {
    // oadrRequestEventType
    // 

    const oadrRequestEventType::eiRequestEvent_type& oadrRequestEventType::
    eiRequestEvent () const
    {
      return this->eiRequestEvent_.get ();
    }

    oadrRequestEventType::eiRequestEvent_type& oadrRequestEventType::
    eiRequestEvent ()
    {
      return this->eiRequestEvent_.get ();
    }

    void oadrRequestEventType::
    eiRequestEvent (const eiRequestEvent_type& x)
    {
      this->eiRequestEvent_.set (x);
    }

    void oadrRequestEventType::
    eiRequestEvent (::std::unique_ptr< eiRequestEvent_type > x)
    {
      this->eiRequestEvent_.set (std::move (x));
    }

    const oadrRequestEventType::schemaVersion_optional& oadrRequestEventType::
    schemaVersion () const
    {
      return this->schemaVersion_;
    }

    oadrRequestEventType::schemaVersion_optional& oadrRequestEventType::
    schemaVersion ()
    {
      return this->schemaVersion_;
    }

    void oadrRequestEventType::
    schemaVersion (const schemaVersion_type& x)
    {
      this->schemaVersion_.set (x);
    }

    void oadrRequestEventType::
    schemaVersion (const schemaVersion_optional& x)
    {
      this->schemaVersion_ = x;
    }

    void oadrRequestEventType::
    schemaVersion (::std::unique_ptr< schemaVersion_type > x)
    {
      this->schemaVersion_.set (std::move (x));
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    // oadrRequestEventType
    //

    oadrRequestEventType::
    oadrRequestEventType (const eiRequestEvent_type& eiRequestEvent)
    : ::xml_schema::type (),
      eiRequestEvent_ (eiRequestEvent, this),
      schemaVersion_ (this)
    {
    }

    oadrRequestEventType::
    oadrRequestEventType (::std::unique_ptr< eiRequestEvent_type > eiRequestEvent)
    : ::xml_schema::type (),
      eiRequestEvent_ (std::move (eiRequestEvent), this),
      schemaVersion_ (this)
    {
    }

    oadrRequestEventType::
    oadrRequestEventType (const oadrRequestEventType& x,
                          ::xml_schema::flags f,
                          ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      eiRequestEvent_ (x.eiRequestEvent_, f, this),
      schemaVersion_ (x.schemaVersion_, f, this)
    {
    }

    oadrRequestEventType::
    oadrRequestEventType (const ::xercesc::DOMElement& e,
                          ::xml_schema::flags f,
                          ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      eiRequestEvent_ (this),
      schemaVersion_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void oadrRequestEventType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // eiRequestEvent
        //
        if (n.name () == "eiRequestEvent" && n.namespace_ () == "http://docs.oasis-open.org/ns/energyinterop/201110/payloads")
        {
          ::std::unique_ptr< eiRequestEvent_type > r (
            eiRequestEvent_traits::create (i, f, this));

          if (!eiRequestEvent_.present ())
          {
            this->eiRequestEvent_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!eiRequestEvent_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "eiRequestEvent",
          "http://docs.oasis-open.org/ns/energyinterop/201110/payloads");
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "schemaVersion" && n.namespace_ () == "http://docs.oasis-open.org/ns/energyinterop/201110")
        {
          this->schemaVersion_.set (schemaVersion_traits::create (i, f, this));
          continue;
        }
      }
    }

    oadrRequestEventType* oadrRequestEventType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class oadrRequestEventType (*this, f, c);
    }

    oadrRequestEventType& oadrRequestEventType::
    operator= (const oadrRequestEventType& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->eiRequestEvent_ = x.eiRequestEvent_;
        this->schemaVersion_ = x.schemaVersion_;
      }

      return *this;
    }

    oadrRequestEventType::
    ~oadrRequestEventType ()
    {
    }
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    ::std::ostream&
    operator<< (::std::ostream& o, const oadrRequestEventType& i)
    {
      o << ::std::endl << "eiRequestEvent: " << i.eiRequestEvent ();
      if (i.schemaVersion ())
      {
        o << ::std::endl << "schemaVersion: " << *i.schemaVersion ();
      }

      return o;
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace oadr2b
{
  namespace oadr
  {
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    void
    operator<< (::xercesc::DOMElement& e, const oadrRequestEventType& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // eiRequestEvent
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "eiRequestEvent",
            "http://docs.oasis-open.org/ns/energyinterop/201110/payloads",
            e));

        s << i.eiRequestEvent ();
      }

      // schemaVersion
      //
      if (i.schemaVersion ())
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "schemaVersion",
            "http://docs.oasis-open.org/ns/energyinterop/201110",
            e));

        a << *i.schemaVersion ();
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

