// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "oadrEvent.hxx"

#include "eiEventType.hxx"

#include "ResponseRequiredType.hxx"

namespace oadr2b
{
  namespace oadr
  {
    // oadrEvent
    // 

    const oadrEvent::eiEvent_type& oadrEvent::
    eiEvent () const
    {
      return this->eiEvent_.get ();
    }

    oadrEvent::eiEvent_type& oadrEvent::
    eiEvent ()
    {
      return this->eiEvent_.get ();
    }

    void oadrEvent::
    eiEvent (const eiEvent_type& x)
    {
      this->eiEvent_.set (x);
    }

    void oadrEvent::
    eiEvent (::std::unique_ptr< eiEvent_type > x)
    {
      this->eiEvent_.set (std::move (x));
    }

    const oadrEvent::oadrResponseRequired_type& oadrEvent::
    oadrResponseRequired () const
    {
      return this->oadrResponseRequired_.get ();
    }

    oadrEvent::oadrResponseRequired_type& oadrEvent::
    oadrResponseRequired ()
    {
      return this->oadrResponseRequired_.get ();
    }

    void oadrEvent::
    oadrResponseRequired (const oadrResponseRequired_type& x)
    {
      this->oadrResponseRequired_.set (x);
    }

    void oadrEvent::
    oadrResponseRequired (::std::unique_ptr< oadrResponseRequired_type > x)
    {
      this->oadrResponseRequired_.set (std::move (x));
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    // oadrEvent
    //

    oadrEvent::
    oadrEvent (const eiEvent_type& eiEvent,
               const oadrResponseRequired_type& oadrResponseRequired)
    : ::xml_schema::type (),
      eiEvent_ (eiEvent, this),
      oadrResponseRequired_ (oadrResponseRequired, this)
    {
    }

    oadrEvent::
    oadrEvent (::std::unique_ptr< eiEvent_type > eiEvent,
               const oadrResponseRequired_type& oadrResponseRequired)
    : ::xml_schema::type (),
      eiEvent_ (std::move (eiEvent), this),
      oadrResponseRequired_ (oadrResponseRequired, this)
    {
    }

    oadrEvent::
    oadrEvent (const oadrEvent& x,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      eiEvent_ (x.eiEvent_, f, this),
      oadrResponseRequired_ (x.oadrResponseRequired_, f, this)
    {
    }

    oadrEvent::
    oadrEvent (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      eiEvent_ (this),
      oadrResponseRequired_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void oadrEvent::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // eiEvent
        //
        if (n.name () == "eiEvent" && n.namespace_ () == "http://docs.oasis-open.org/ns/energyinterop/201110")
        {
          ::std::unique_ptr< eiEvent_type > r (
            eiEvent_traits::create (i, f, this));

          if (!eiEvent_.present ())
          {
            this->eiEvent_.set (::std::move (r));
            continue;
          }
        }

        // oadrResponseRequired
        //
        if (n.name () == "oadrResponseRequired" && n.namespace_ () == "http://openadr.org/oadr-2.0b/2012/07")
        {
          ::std::unique_ptr< oadrResponseRequired_type > r (
            oadrResponseRequired_traits::create (i, f, this));

          if (!oadrResponseRequired_.present ())
          {
            this->oadrResponseRequired_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!eiEvent_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "eiEvent",
          "http://docs.oasis-open.org/ns/energyinterop/201110");
      }

      if (!oadrResponseRequired_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "oadrResponseRequired",
          "http://openadr.org/oadr-2.0b/2012/07");
      }
    }

    oadrEvent* oadrEvent::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class oadrEvent (*this, f, c);
    }

    oadrEvent& oadrEvent::
    operator= (const oadrEvent& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->eiEvent_ = x.eiEvent_;
        this->oadrResponseRequired_ = x.oadrResponseRequired_;
      }

      return *this;
    }

    oadrEvent::
    ~oadrEvent ()
    {
    }
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    ::std::ostream&
    operator<< (::std::ostream& o, const oadrEvent& i)
    {
      o << ::std::endl << "eiEvent: " << i.eiEvent ();
      o << ::std::endl << "oadrResponseRequired: " << i.oadrResponseRequired ();
      return o;
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace oadr2b
{
  namespace oadr
  {
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    void
    operator<< (::xercesc::DOMElement& e, const oadrEvent& i)
    {
      e << static_cast< const ::xml_schema::type& > (i);

      // eiEvent
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "eiEvent",
            "http://docs.oasis-open.org/ns/energyinterop/201110",
            e));

        s << i.eiEvent ();
      }

      // oadrResponseRequired
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "oadrResponseRequired",
            "http://openadr.org/oadr-2.0b/2012/07",
            e));

        s << i.oadrResponseRequired ();
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

