// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "oadrReportPayloadType.hxx"

#include "oadrDataQualityTypeType.hxx"

namespace oadr2b
{
  namespace oadr
  {
    // oadrReportPayloadType
    // 

    const oadrReportPayloadType::oadrDataQuality_optional& oadrReportPayloadType::
    oadrDataQuality () const
    {
      return this->oadrDataQuality_;
    }

    oadrReportPayloadType::oadrDataQuality_optional& oadrReportPayloadType::
    oadrDataQuality ()
    {
      return this->oadrDataQuality_;
    }

    void oadrReportPayloadType::
    oadrDataQuality (const oadrDataQuality_type& x)
    {
      this->oadrDataQuality_.set (x);
    }

    void oadrReportPayloadType::
    oadrDataQuality (const oadrDataQuality_optional& x)
    {
      this->oadrDataQuality_ = x;
    }

    void oadrReportPayloadType::
    oadrDataQuality (::std::unique_ptr< oadrDataQuality_type > x)
    {
      this->oadrDataQuality_.set (std::move (x));
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    // oadrReportPayloadType
    //

    oadrReportPayloadType::
    oadrReportPayloadType (const rID_type& rID,
                           const payloadBase_type& payloadBase)
    : ::oadr2b::ei::ReportPayloadType (rID,
                                       payloadBase),
      oadrDataQuality_ (this)
    {
    }

    /*oadrReportPayloadType::
    oadrReportPayloadType (const rID_type& rID,
                           ::std::unique_ptr< payloadBase_type > payloadBase)
    : ::oadr2b::ei::ReportPayloadType (rID,
                                       std::move (payloadBase)),
      oadrDataQuality_ (this)
    {
    }*/

    oadrReportPayloadType::
    oadrReportPayloadType (const oadrReportPayloadType& x,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
    : ::oadr2b::ei::ReportPayloadType (x, f, c),
      oadrDataQuality_ (x.oadrDataQuality_, f, this)
    {
    }

    oadrReportPayloadType::
    oadrReportPayloadType (const ::xercesc::DOMElement& e,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
    : ::oadr2b::ei::ReportPayloadType (e, f | ::xml_schema::flags::base, c),
      oadrDataQuality_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void oadrReportPayloadType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      this->::oadr2b::ei::ReportPayloadType::parse (p, f);

      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // oadrDataQuality
        //
        if (n.name () == "oadrDataQuality" && n.namespace_ () == "http://openadr.org/oadr-2.0b/2012/07")
        {
          ::std::unique_ptr< oadrDataQuality_type > r (
            oadrDataQuality_traits::create (i, f, this));

          if (!this->oadrDataQuality_)
          {
            this->oadrDataQuality_.set (::std::move (r));
            continue;
          }
        }

        break;
      }
    }

    oadrReportPayloadType* oadrReportPayloadType::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class oadrReportPayloadType (*this, f, c);
    }

    oadrReportPayloadType& oadrReportPayloadType::
    operator= (const oadrReportPayloadType& x)
    {
      if (this != &x)
      {
        static_cast< ::oadr2b::ei::ReportPayloadType& > (*this) = x;
        this->oadrDataQuality_ = x.oadrDataQuality_;
      }

      return *this;
    }

    oadrReportPayloadType::
    ~oadrReportPayloadType ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, char, oadrReportPayloadType >
    _xsd_oadrReportPayloadType_type_factory_init (
      "oadrReportPayloadType",
      "http://openadr.org/oadr-2.0b/2012/07");
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    ::std::ostream&
    operator<< (::std::ostream& o, const oadrReportPayloadType& i)
    {
      o << static_cast< const ::oadr2b::ei::ReportPayloadType& > (i);

      if (i.oadrDataQuality ())
      {
        o << ::std::endl << "oadrDataQuality: " << *i.oadrDataQuality ();
      }

      return o;
    }

    static
    const ::xsd::cxx::tree::std_ostream_initializer< 0, char, oadrReportPayloadType >
    _xsd_oadrReportPayloadType_std_ostream_init;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace oadr2b
{
  namespace oadr
  {
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace oadr2b
{
  namespace oadr
  {
    void
    operator<< (::xercesc::DOMElement& e, const oadrReportPayloadType& i)
    {
      e << static_cast< const ::oadr2b::ei::ReportPayloadType& > (i);

      // oadrDataQuality
      //
      if (i.oadrDataQuality ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "oadrDataQuality",
            "http://openadr.org/oadr-2.0b/2012/07",
            e));

        s << *i.oadrDataQuality ();
      }
    }

    static
    const ::xsd::cxx::tree::type_serializer_initializer< 0, char, oadrReportPayloadType >
    _xsd_oadrReportPayloadType_type_serializer_init (
      "oadrReportPayloadType",
      "http://openadr.org/oadr-2.0b/2012/07");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

