// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "StreamBaseType.hxx"

#include "dtstart.hxx"

#include "DurationPropType.hxx"

#include "intervals.hxx"

namespace stream
{
  // StreamBaseType
  // 

  const StreamBaseType::dtstart_optional& StreamBaseType::
  dtstart () const
  {
    return this->dtstart_;
  }

  StreamBaseType::dtstart_optional& StreamBaseType::
  dtstart ()
  {
    return this->dtstart_;
  }

  void StreamBaseType::
  dtstart (const dtstart_type& x)
  {
    this->dtstart_.set (x);
  }

  void StreamBaseType::
  dtstart (const dtstart_optional& x)
  {
    this->dtstart_ = x;
  }

  void StreamBaseType::
  dtstart (::std::unique_ptr< dtstart_type > x)
  {
    this->dtstart_.set (std::move (x));
  }

  const StreamBaseType::duration_optional& StreamBaseType::
  duration () const
  {
    return this->duration_;
  }

  StreamBaseType::duration_optional& StreamBaseType::
  duration ()
  {
    return this->duration_;
  }

  void StreamBaseType::
  duration (const duration_type& x)
  {
    this->duration_.set (x);
  }

  void StreamBaseType::
  duration (const duration_optional& x)
  {
    this->duration_ = x;
  }

  void StreamBaseType::
  duration (::std::unique_ptr< duration_type > x)
  {
    this->duration_.set (std::move (x));
  }

  const StreamBaseType::intervals_optional& StreamBaseType::
  intervals () const
  {
    return this->intervals_;
  }

  StreamBaseType::intervals_optional& StreamBaseType::
  intervals ()
  {
    return this->intervals_;
  }

  void StreamBaseType::
  intervals (const intervals_type& x)
  {
    this->intervals_.set (x);
  }

  void StreamBaseType::
  intervals (const intervals_optional& x)
  {
    this->intervals_ = x;
  }

  void StreamBaseType::
  intervals (::std::unique_ptr< intervals_type > x)
  {
    this->intervals_.set (std::move (x));
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace stream
{
  // StreamBaseType
  //

  StreamBaseType::
  StreamBaseType ()
  : ::xml_schema::type (),
    dtstart_ (this),
    duration_ (this),
    intervals_ (this)
  {
  }

  StreamBaseType::
  StreamBaseType (const StreamBaseType& x,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    dtstart_ (x.dtstart_, f, this),
    duration_ (x.duration_, f, this),
    intervals_ (x.intervals_, f, this)
  {
  }

  StreamBaseType::
  StreamBaseType (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    dtstart_ (this),
    duration_ (this),
    intervals_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void StreamBaseType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // dtstart
      //
      if (n.name () == "dtstart" && n.namespace_ () == "urn:ietf:params:xml:ns:icalendar-2.0")
      {
        ::std::unique_ptr< dtstart_type > r (
          dtstart_traits::create (i, f, this));

        if (!this->dtstart_)
        {
          this->dtstart_.set (::std::move (r));
          continue;
        }
      }

      // duration
      //
      if (n.name () == "duration" && n.namespace_ () == "urn:ietf:params:xml:ns:icalendar-2.0")
      {
        ::std::unique_ptr< duration_type > r (
          duration_traits::create (i, f, this));

        if (!this->duration_)
        {
          this->duration_.set (::std::move (r));
          continue;
        }
      }

      // intervals
      //
      if (n.name () == "intervals" && n.namespace_ () == "urn:ietf:params:xml:ns:icalendar-2.0:stream")
      {
        ::std::unique_ptr< intervals_type > r (
          intervals_traits::create (i, f, this));

        if (!this->intervals_)
        {
          this->intervals_.set (::std::move (r));
          continue;
        }
      }

      break;
    }
  }

  StreamBaseType* StreamBaseType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class StreamBaseType (*this, f, c);
  }

  StreamBaseType& StreamBaseType::
  operator= (const StreamBaseType& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->dtstart_ = x.dtstart_;
      this->duration_ = x.duration_;
      this->intervals_ = x.intervals_;
    }

    return *this;
  }

  StreamBaseType::
  ~StreamBaseType ()
  {
  }
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

namespace stream
{
  ::std::ostream&
  operator<< (::std::ostream& o, const StreamBaseType& i)
  {
    if (i.dtstart ())
    {
      o << ::std::endl << "dtstart: " << *i.dtstart ();
    }

    if (i.duration ())
    {
      o << ::std::endl << "duration: " << *i.duration ();
    }

    if (i.intervals ())
    {
      o << ::std::endl << "intervals: " << *i.intervals ();
    }

    return o;
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace stream
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

#include <xsd/cxx/tree/type-serializer-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_serializer_plate< 0, char >
  type_serializer_plate_init;
}

namespace stream
{
  void
  operator<< (::xercesc::DOMElement& e, const StreamBaseType& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // dtstart
    //
    if (i.dtstart ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "dtstart",
          "urn:ietf:params:xml:ns:icalendar-2.0",
          e));

      s << *i.dtstart ();
    }

    // duration
    //
    if (i.duration ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "duration",
          "urn:ietf:params:xml:ns:icalendar-2.0",
          e));

      s << *i.duration ();
    }

    // intervals
    //
    if (i.intervals ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "intervals",
          "urn:ietf:params:xml:ns:icalendar-2.0:stream",
          e));

      s << *i.intervals ();
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

