import glob
import os
import sconsHelper

Import('cflags buildmode')

cppPath = ['helper', '#oadr', '#oadrsd', '../xsd-4.0.0']
libDir = ['../oadr/' + buildmode, '../oadrsd/' + buildmode]
libs = ['oadr', 'ssl', 'crypto', 'pthread', 'curl', 'xerces-c', 'oadrsd']

sconsHelper.build('sample', cppPath, cflags, libDir, libs, buildmode, "program")

